### ISSUE TITLE
rabbitmq_vhost state deprecated policy arguments

### ISSUE THREAD

**Issue by syphernl** [saltstack-formulas/rabbitmq-formula#18]
According to the source of `rabbitmq_vhost.py` the parameters are deprecated:
```
            'Passed \'owner\', \'user\', \'conf\', \'write\' or \'read\' '
            'arguments. These are being deprecated, and will be removed in '
            'Salt Beryllium. Please update your state files, and set '
            'permissions for user instead. See rabbitmq_user.present.
```

Since this formula uses `rabbitmq_vhost.present` in the `config.sls` this may need to be updated soonish to prevent the formula from breaking when Salt reaches Beryllium.

**Comment by ramonamis** [comment]
Hello, please check: https://github.com/saltstack-formulas/rabbitmq-formula/pull/19

**Comment by gravyboat** [comment]
Closing this since #19 is merged. Thanks for the report @syphernl.
