### ISSUE TITLE
rabbitmq_vhost: All arguments deprecated in Salt 2015.8.0

### ISSUE THREAD

**Issue by syphernl** [saltstack-formulas/rabbitmq-formula#34]
According to the [documentation of state rabbitmq_vhost](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.rabbitmq_vhost.html) *all* arguments (e.g. `user`, `owner`, `write` etc) have all been deprecated and now results in a warning when a highstate is being executed about it being removed in the next (stable) release.

**Comment by gravyboat** [comment]
We'll need to replace those all with items from the following:
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.rabbitmq_cluster.html
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.rabbitmq_plugin.html
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.rabbitmq_policy.html
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.rabbitmq_user.html

I've also created https://github.com/saltstack/salt/issues/27857. Thanks for bringing this up.

**Comment by jaygorrell** [comment]
Any chance the above PR will ever get merged? It's been open since the beginning of the year and has been verified to work by different users who tried it.

**Comment by gravyboat** [comment]
@jaygorrell Looks like it got overlooked for some reason after there was discussion. I've merged it.

**Comment by gravyboat** [comment]
@jaygorrell Looks like it got overlooked for some reason after there was discussion. I've merged it.
